language: ruby
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
- jruby
- rbx-2
matrix:
  allow_failures:
  - rvm: rbx-2
addons:
  code_climate:
    repo_token: 151a667c2c51ff76ac825c07c33e8e63c1ae9956a73f4d0ec7a043d877d05c95
notifications:
  slack:
    secure: Ykcz/gLRZcXhyOGedVgj1u3CDUbZS4y/nL1dREBE0Ar73Vrz+ulcMhri3VzfVBQGkWw06EjqHcIwsIomEInLJKxk3RTfpcYQAdYN+5iEDNOri9a5NK618WdrCuaCS3sKqYbJ/KB0slJDcJ1W+EXkr4GRqZTr5rPdmllUnoaqDCQ=
